### ISSUE TITLE
Introduce scatter / plot separation

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/EcologicalNetworksPlots.jl#1]
Ideally, `scatter` would plot the points, and `plot` the lines -- this opens a few interesting possibilities.

**Comment by tpoisot** [comment]
@mkborregaard I'm most likely missing something, but what would be the correct way to add a `scatter` and a `plot` method for custom types?

**Comment by mkborregaard** [comment]
I'm not sure what you want to achieve exactly. If you do want to do exactly this, the best way is to just define the recipe on the type, then check `if plotattributes[:seriestype] == :scatter` and branch from there, since `scatter(myobj)` is just a call to `plot(myobj, seriestype = :scatter)`.

**Comment by mkborregaard** [comment]
BTW we are refactoring to be only about plotting graphs and factoring out the dependencies on Plots and StatPlots. There is a lot of functionality in there (and in NetworkLayout) that should be useful here. Have you had a look?

**Comment by tpoisot** [comment]
Thanks -- I was looking for a way to separate the plotting of edges (`plot`) and nodes (`scatter`). I might end up using what's in `NetworkLayout`.

**Comment by mkborregaard** [comment]
(in principle it's better to check `markershape` than `seriestype` since it's common to do `plot(myobj, marker = :circle)` to add markers to a plot - like I do in the Phylo recipes [ https://github.com/richardreeve/Phylo.jl/pull/15 ]). I love the plots you're creating here btw, so pretty!
