### ISSUE TITLE
Add a method for annotation!

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/EcologicalNetworksPlots.jl#11]
In some cases, it would be useful to be able to label some nodes on the network, which can be done with `annotate!(L, N)` where `L` is a layout, and `N` is a network (or a subset of it).

This can probably be done with a recipe, but I'm not finding this info anywhere in the doc -- @mkborregaard do you have more info about where I should look?

**Comment by mkborregaard** [comment]
Maybe using `series_annotations`? That's the approach that GraphRecipes takes for it's `names` argument

**Comment by tpoisot** [comment]
I see - this is something I should add to the recipe using something similar to https://github.com/PoisotLab/EcologicalNetworksPlots.jl/blob/master/src/recipes.jl#L42 ?

**Comment by mkborregaard** [comment]
what happens if you just specify `series_annotations = string.(1:number_of_nodes)`in the plot call?

**Comment by tpoisot** [comment]
good question, I'll try this - is there a way to turn it on and off when calling *e.g.* `scatter`?

**Comment by tpoisot** [comment]
I'll try.

**Comment by tpoisot** [comment]
Yep, that's working - thanks @mkborregaard
